GET http://localhost:8081/favorites/josue3
###
GET http://localhost:8081/favorites/josue3/455
###
POST http://localhost:8081/favorites/create
Content-Type: application/json

{
    "username": "josue3",
    "favoriteName": "455",
    "direction" : "Outbound"
}
###
GET http://localhost:8081/favorites/josue3/455
###
PATCH http://localhost:8081/favorites/editFavorite
Content-Type: application/json

{
    "username": "josue3",
    "favoriteName": "455",
    "direction" : "Outbound"
}
###
DELETE http://localhost:8081/favorites/deleteFavorite
Content-Type: application/json

{
    "username": "josue3",
    "favoriteName": "455"
}
###
GET http://localhost:8081/favorites/josue3/455
###